// <auto-generated />
using System;
using IDN.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ContextApp))]
    [Migration("20231024181327_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IDN.Core.Empresa.Models.MEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CEP")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("varchar(14)");

                    b.Property<decimal?>("CapitalSocial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CnaeDescricao")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CnaeFiscalPrincipal")
                        .HasColumnType("varchar(7)");

                    b.Property<string>("DataExclusaoMEI")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("DataExclusaoSimples")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("DataInicioAtividade")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("DataOpcaoMEI")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("DataOpcaoSimples")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("DataSituacaoCadastral")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("IdentificadorMatrizFilial")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Municipio")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("OpcaoMEI")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("OpcaoSimples")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("PorteEmpresa")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SituacaoCadastral")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("UF")
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("IDN.Core.Municipio.Models.MMunicipio", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
