version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=sql@123
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONNECT_ADDR=postgres
    ports:
      - "80:80"